import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import ClientProviders from "@/components/ClientProviders";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import Ripple from "@/components/ui/ripple";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body className={cn("min-h-screen font-sans antialiased grainy", ``)}>
          <Ripple />
          <ClientProviders>
            <Navbar />
            {children}
          </ClientProviders>
        </body>
      </Providers>
    </html>
  );
}
